language: python

os:
  - linux

arch:
  - amd64

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

matrix:
  include:
    - python: "3.5"
      install: CC=clang python -m pip install . --no-deps -vv
    - python: "3.8"
      install: CC=clang python -m pip install . --no-deps -vv
    - python: "3.8"
      arch: arm64
    - python: "3.8"
      os: linux-ppc64le
      arch: ppc64le
    - python: "3.8"
      arch: s390x

before_install:
  - python -m pip install pip setuptools --upgrade

install:
  - python -m pip install . --no-deps -vv

# command to run tests
script:
  - python -m pip install pytest --upgrade
  - python -m pytest tests/
