language: python

os:
  - linux

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6-dev"
  - "nightly"

matrix:
  # osx is very slow at the moment.
  #include:
    #- python: "2.7"
    #  os: osx
    #- python: "3.5"
    #  os: osx

  allow_failures:
    - python: "3.6-dev"
    - python: "nightly"

install:
  - pip install coveralls
  - python setup.py install

# command to run tests
script:
  - coverage run --source=iteration_utilities setup.py test

after_success:
  coveralls
