language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

matrix:
  include:
    - python: "2.7"
      install: CC=clang python -m pip install . --no-deps -vv
    - python: "3.7"
      install: CC=clang python -m pip install . --no-deps -vv

before_install:
  - python -m pip install pip setuptools --upgrade

install:
  - python -m pip install . --no-deps -vv

# command to run tests
script:
  - python -m pytest tests/
