name: Benchmark (CPython)

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master


jobs:
  run-benchmarks:
    runs-on: ubuntu-18.04
    timeout-minutes: 15

    steps:
    - name: Check out source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install pip setuptools wheel --upgrade
    - name: Install package
      run: |
        python -m pip install .
    - name: Install benchmark dependencies
      run: |
        python -m pip install simple_benchmark[optional]
    - name: Install other packages dependencies
      run: |
        python -m pip install cython
    - name: Install other packages
      run: |
        python -m pip install more-itertools toolz cytoolz
    - name: Run benchmarks
      run: |
        python ./ci/collect_benchmarks.py
    - name: Upload results
      uses: actions/upload-artifact@master
      with:
        name: py3.7-benchmarks
        path: ./.benchmark_results/
