name: Python (CPython)

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master


jobs:

  build-clang:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 6
      matrix:
        os: [macOS-10.14]
        python-version: [2.7, 3.7]

    steps:
    - name: Check out source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pip setuptools --upgrade
    - name: Install package
      run: |
        CC=clang python -m pip install . --no-deps -vv
    - name: Import package
      run: |
        python -c "import iteration_utilities"
    - name: Install test dependencies
      run: |
        python -m pip install pytest
    - name: Run tests
      run: |
        python -m pytest tests/

  build-sdist:
    runs-on: windows-2019
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Check out source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pip setuptools wheel --upgrade
    - name: Create source distribution
      run: |
        python setup.py sdist
    - name: Install package
      run: |
        python -m pip install --no-index --find-links=./dist/ iteration_utilities -vv
    - name: Import package
      run: |
        python -c "import iteration_utilities"
    - name: Install test dependencies
      run: |
        python -m pip install pytest
    - name: Run tests
      run: |
        python -m pytest tests/
    - name: Upload dist
      uses: actions/upload-artifact@master
      with:
        name: py_sdist
        path: ./dist/


  build-manylinux:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    strategy:
      matrix:
        docker-image: [manylinux1_x86_64, manylinux1_i686, manylinux2010_x86_64]

    steps:
      - name: Check out source
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Get Docker image
        run: |
          docker pull quay.io/pypa/${{ matrix.docker-image }}
      - name: Build in Docker
        run: |
          docker run --rm \
          -e PLAT=${{ matrix.docker-image }} \
          -v $(pwd):/io \
          quay.io/pypa/${{ matrix.docker-image }} \
          /bin/bash -c "$(cat ./ci/build-wheels.sh)"
        if: matrix.docker-image != 'manylinux1_i686'
      - name: Build in Docker
        run: |
          docker run --rm \
          -e PLAT=${{ matrix.docker-image }} \
          -v $(pwd):/io \
          quay.io/pypa/${{ matrix.docker-image }} \
          linux32 /bin/bash -c "$(cat ./ci/build-wheels.sh)"
        if: matrix.docker-image == 'manylinux1_i686'
      - name: Upload wheels
        uses: actions/upload-artifact@master
        with:
          name: py${{ matrix.docker-image }}
          path: ./wheelhouse/


  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 6
      matrix:
        os: [windows-2019, ubuntu-18.04, macOS-10.14]
        python-version: [2.7, 3.6, 3.7]
        architecture: [x64, x86]
        exclude:
          - architecture: x86
            os: macOS-10.14
          - architecture: x86
            os: ubuntu-18.04

    steps:
    - name: Check out source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install VC
      if: matrix.os == 'windows-2019' && matrix.python-version == 2.7
      run: |
        choco install vcpython27 --yes --no-progress
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
        python -m pip install pip setuptools wheel --upgrade
    - name: Create wheel
      run: |
        python -m pip wheel . --no-deps --wheel-dir=./wheelhouse/ -vv
    - name: Install package
      run: |
        python -m pip install iteration_utilities --no-index --find-links=./wheelhouse/ -vv
    - name: Import package
      run: |
        python -c "import iteration_utilities"
    - name: Install test dependencies
      run: |
        python -m pip install pytest
    - name: Run tests
      run: |
        python -m pytest tests/
    - name: Upload wheel
      uses: actions/upload-artifact@master
      if: matrix.os != 'ubuntu-18.04'
      with:
        name: py${{ matrix.python-version }}-${{ matrix.architecture }}-${{ matrix.os }}
        path: ./wheelhouse/


  coverage:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-18.04]
        python-version: [2.7, 3.6, 3.7]

    steps:
    - name: Check out source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pip setuptools --upgrade
    - name: Install package
      run: |
        CFLAGS="-coverage" python setup.py install # TODO: Check if there's a way with pip install
    - name: Install test dependencies
      run: |
        python -m pip install pytest pytest-cov
    - name: Run tests
      run: |
        python -m pytest tests/ --cov=iteration_utilities --cov-report=xml --cov-config=./setup.cfg
    - name: Upload Coverage report
      # It would probably be better to use the codecov-action but that's very slow:
      # https://github.com/codecov/codecov-action/issues/21
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -F unittests -n ${{ matrix.os }}-${{ matrix.python-version }}


  build-docs:
    runs-on: windows-2019
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.7]
        architecture: [x86]

    steps:
    - name: Check out source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Install dependencies
      run: |
        python -m pip install pip setuptools --upgrade
    - name: Install package
      run: |
        python -m pip install . --no-deps -vv
    - name: Install doc dependencies
      run: |
        python -m pip install sphinx numpydoc
    - name: Build doc
      run: |
        python setup.py build_sphinx
    - name: Upload documentation
      uses: actions/upload-artifact@master
      with:
        name: docs
        path: ./build/sphinx/html/


  build-py38-windows:
    runs-on: windows-2019
    timeout-minutes: 10
    strategy:
      matrix:
        architecture: [x86, x64]

    steps:
    - name: Check out source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Download Python 3.8 (x86)
      if: matrix.architecture == 'x86'
      run: |
        curl https://www.python.org/ftp/python/3.8.0/python-3.8.0.exe --output pythoninstaller.exe
        python ci/verify_checksum.py pythoninstaller.exe 412a649d36626d33b8ca5593cf18318c
    - name: Install Python 3.8 (x86)
      if: matrix.architecture == 'x86'
      run: |
        pythoninstaller.exe /passive TargetDir=%LocalAppData%\Programs\Python38 AssociateFiles=0 CompileAll=0 PrependPath=1 Shortcuts=0 Include_doc=0 Include_debug=0 Include_dev=1 Include_exe=1 Include_launcher=0 Include_lib=1 Include_pip=1 Include_symbols=0 Include_tcltk=0 Include_test=0 Include_tools=0
    - name: Download Python 3.8 (x64)
      if: matrix.architecture == 'x64'
      run: |
        curl https://www.python.org/ftp/python/3.8.0/python-3.8.0-amd64.exe --output pythoninstaller.exe
        python ci/verify_checksum.py pythoninstaller.exe 29ea87f24c32f5e924b7d63f8a08ee8d
    - name: Install Python 3.8 (x64)
      if: matrix.architecture == 'x64'
      run: |
        pythoninstaller.exe /passive TargetDir=%LocalAppData%\Programs\Python38 AssociateFiles=0 CompileAll=0 PrependPath=1 Shortcuts=0 Include_doc=0 Include_debug=0 Include_dev=1 Include_exe=1 Include_launcher=0 Include_lib=1 Include_pip=1 Include_symbols=0 Include_tcltk=0 Include_test=0 Include_tools=0
    - name: Remove download
      run: |
        python -c "import os; os.remove('./pythoninstaller.exe')"
    - name: Install dependencies
      run: |
        "%LocalAppData%\Programs\Python38\python.exe" -m pip install pip setuptools wheel --upgrade
    - name: Create wheel
      run: |
        "%LocalAppData%\Programs\Python38\python.exe" -m pip wheel . --no-deps --wheel-dir=./wheelhouse/ -vv
    - name: Install package
      run: |
        "%LocalAppData%\Programs\Python38\python.exe" -m pip install iteration_utilities --no-index --find-links=./wheelhouse/ -vv
    - name: Import package
      run: |
        "%LocalAppData%\Programs\Python38\python.exe" -c "import iteration_utilities"
    - name: Install test dependencies
      run: |
        "%LocalAppData%\Programs\Python38\python.exe" -m pip install pytest
    - name: Run tests
      run: |
        "%LocalAppData%\Programs\Python38\python.exe" -m pytest tests/
    - name: Upload wheel
      uses: actions/upload-artifact@master
      with:
        name: py3.8-${{ matrix.architecture }}-windows-2019
        path: ./wheelhouse/


  build-py38-ubuntu:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
    - name: Check out source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Download Python 3.8
      run: |
        wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz -q
        python3 ci/verify_checksum.py Python-3.8.0.tgz e18a9d1a0a6d858b9787e03fc6fdaa20
    - name: Install Python 3.8
      run: |
        tar xzf Python-3.8.0.tgz
        cd Python-3.8.0
        ./configure --enable-optimizations
        sudo make altinstall
    - name: Remove download
      run: |
        sudo python3.8 -c "import os; os.remove('./Python-3.8.0.tgz'); import shutil; shutil.rmtree('./Python-3.8.0/')"
    - name: Install dependencies
      run: |
        python3.8 -m pip install pip setuptools wheel --upgrade --user
    - name: Create wheel
      run: |
        python3.8 -m pip wheel . --no-deps --wheel-dir=./wheelhouse/ -vv
    - name: Install package
      run: |
        python3.8 -m pip install iteration_utilities --no-index --find-links=./wheelhouse/ --user -vv
    - name: Import package
      run: |
        python3.8 -c "import iteration_utilities"
    - name: Install test dependencies
      run: |
        python3.8 -m pip install pytest --user
    - name: Run tests
      run: |
        python3.8 -m pytest tests/


  build-py38-ubuntu-coverage:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
    - name: Check out source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Download Python 3.8
      run: |
        wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz -q
        python3 ci/verify_checksum.py Python-3.8.0.tgz e18a9d1a0a6d858b9787e03fc6fdaa20
    - name: Install Python 3.8
      run: |
        tar xzf Python-3.8.0.tgz
        cd Python-3.8.0
        ./configure --enable-optimizations
        sudo make altinstall
    - name: Remove download
      run: |
        sudo python3.8 -c "import os; os.remove('./Python-3.8.0.tgz'); import shutil; shutil.rmtree('./Python-3.8.0/')"
    - name: Install dependencies
      run: |
        python3.8 -m pip install pip setuptools wheel --upgrade --user
    - name: Install package
      run: |
        CFLAGS="-coverage" python3.8 setup.py install --user
    - name: Install test dependencies
      run: |
        python3.8 -m pip install pytest pytest-cov --user
    - name: Run tests
      run: |
        python3.8 -m pytest tests/ --cov=iteration_utilities --cov-report=xml --cov-config=./setup.cfg
    - name: Upload Coverage report
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -F unittests -n ubuntu-18.04-3.8


  build-py38-macOS:
    runs-on: macOS-10.14
    timeout-minutes: 10

    steps:
    - name: Check out source
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Download Python 3.8
      run: |
        curl https://www.python.org/ftp/python/3.8.0/python-3.8.0-macosx10.9.pkg --output pythoninstaller.pkg
        python3 ci/verify_checksum.py pythoninstaller.pkg f5f9ae9f416170c6355cab7256bb75b5
    - name: Install Python 3.8
      run: |
        sudo installer -pkg pythoninstaller.pkg -target /
    - name: Remove download
      run: |
        python3 -c "import os; os.remove('./pythoninstaller.pkg')"
    - name: Install dependencies
      run: |
        python3.8 -m pip install pip setuptools wheel --upgrade --user
    - name: Create wheel
      run: |
        python3.8 -m pip wheel . --no-deps --wheel-dir=./wheelhouse/ -vv
    - name: Install package
      run: |
        python3.8 -m pip install iteration_utilities --no-index --find-links=./wheelhouse/ --user -vv
    - name: Import package
      run: |
        python3.8 -c "import iteration_utilities"
    - name: Install test dependencies
      run: |
        python3.8 -m pip install pytest --user
    - name: Run tests
      run: |
        python3.8 -m pytest tests/
    - name: Upload wheel
      uses: actions/upload-artifact@master
      with:
        name: py3.8-x64-macOS-10.14
        path: ./wheelhouse/


  bundle-artifacts:
    runs-on: windows-2019
    timeout-minutes: 10
    needs: [build-py38-macOS, build-py38-ubuntu, build-py38-windows, build-docs, build, build-manylinux, build-sdist]

    steps:
    - uses: actions/download-artifact@master
      with:
        name: docs

    - uses: actions/download-artifact@master
      with:
        name: py_sdist
    - run: |
        rename py_sdist sdist

    - run: |
        mkdir wheels
    - uses: actions/download-artifact@master
      with:
        name: pymanylinux1_x86_64
    - run: |
        move pymanylinux1_x86_64\* wheels
        rmdir pymanylinux1_x86_64
    - uses: actions/download-artifact@master
      with:
        name: pymanylinux1_i686
    - run: |
        move pymanylinux1_i686\* wheels
        rmdir pymanylinux1_i686
    - uses: actions/download-artifact@master
      with:
        name: pymanylinux2010_x86_64
    - run: |
        move pymanylinux2010_x86_64\* wheels
        rmdir pymanylinux2010_x86_64
    - uses: actions/download-artifact@master
      with:
        name: py2.7-x64-windows-2019
    - run: |
        move py2.7-x64-windows-2019\* wheels
        rmdir py2.7-x64-windows-2019
    - uses: actions/download-artifact@master
      with:
        name: py2.7-x86-windows-2019
    - run: |
        move py2.7-x86-windows-2019\* wheels
        rmdir py2.7-x86-windows-2019
    - uses: actions/download-artifact@master
      with:
        name: py2.7-x64-macOS-10.14
    - run: |
        move py2.7-x64-macOS-10.14\* wheels
        rmdir py2.7-x64-macOS-10.14
    - uses: actions/download-artifact@master
      with:
        name: py3.6-x64-windows-2019
    - run: |
        move py3.6-x64-windows-2019\* wheels
        rmdir py3.6-x64-windows-2019
    - uses: actions/download-artifact@master
      with:
        name: py3.6-x86-windows-2019
    - run: |
        move py3.6-x86-windows-2019\* wheels
        rmdir py3.6-x86-windows-2019
    - uses: actions/download-artifact@master
      with:
        name: py3.6-x64-macOS-10.14
    - run: |
        move py3.6-x64-macOS-10.14\* wheels
        rmdir py3.6-x64-macOS-10.14
    - uses: actions/download-artifact@master
      with:
        name: py3.7-x64-windows-2019
    - run: |
        move py3.7-x64-windows-2019\* wheels
        rmdir py3.7-x64-windows-2019
    - uses: actions/download-artifact@master
      with:
        name: py3.7-x86-windows-2019
    - run: |
        move py3.7-x86-windows-2019\* wheels
        rmdir py3.7-x86-windows-2019
    - uses: actions/download-artifact@master
      with:
        name: py3.7-x64-macOS-10.14
    - run: |
        move py3.7-x64-macOS-10.14\* wheels
        rmdir py3.7-x64-macOS-10.14
    - uses: actions/download-artifact@master
      with:
        name: py3.8-x64-windows-2019
    - run: |
        move py3.8-x64-windows-2019\* wheels
        rmdir py3.8-x64-windows-2019
    - uses: actions/download-artifact@master
      with:
        name: py3.8-x86-windows-2019
    - run: |
        move py3.8-x86-windows-2019\* wheels
        rmdir py3.8-x86-windows-2019
    - uses: actions/download-artifact@master
      with:
        name: py3.8-x64-macOS-10.14
    - run: |
        move py3.8-x64-macOS-10.14\* wheels
        rmdir py3.8-x64-macOS-10.14
    - name: Upload all
      uses: actions/upload-artifact@master
      with:
        name: all
        path: ./
